import Link from "next/link"

export function UserAgreementContentFr() {
  return (
    &lt;div className="prose prose-lg max-w-none"&gt;
      &lt;p className="text-muted-foreground"&gt;
        &lt;Link href="/user-agreement" className="text-primary hover:underline"&gt;
          Click here to return to the English Version
        &lt;/Link&gt;
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Introduction&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Haven Refugees Incorporated (dénommé « Haven » ou « nous ») vous demande de prendre connaissance du présent contrat de licence d&apos;utilisation qui régit l&apos;utilisation de notre application (telle que décrite ci-dessous). Veuillez noter que pour pouvoir utiliser notre application, vous devez accepter les conditions ci-dessous. Si vous avez des questions, veuillez nous contacter à l&apos;adresse suivante : info@findhaven.org. Bien que nous ne puissions pas répondre à tous les commentaires, nous tiendrons certainement compte de votre contribution et l&apos;utiliserons afin d&apos;améliorer d&apos;avantage l&apos;application Haven.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Haven est un organisme à but non lucratif enregistré en vertu de la Loi canadienne sur les organismes à but non lucratif. Haven a son siège social à Toronto, au Canada. Haven fournit des services de réinsertion aux réfugiés en les mettant en contact avec des intervenants canadiens qui peuvent les aider. Nos services sont offerts par le biais de findhaven.org.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Contrat de licence d&apos;utilisation&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Le présent contrat de licence d&apos;utilisation (le « Contrat ») est une entente légale contraignante entre vous, en tant qu&apos;individu et entité, et Haven, qui régit l&apos;utilisation de l&apos;application Haven (disponible au www.findhaven.org) et tout autre service ou site Web exploité par Haven, y compris tout le contenu, le matériel et les informations qui s&apos;y trouvent ou qui sont liés au présent Contrat (la « Plateforme »). En utilisant la Plateforme de quelque manière que ce soit, vous reconnaissez avoir lu le présent Contrat et vous acceptez d&apos;être lié par celui-ci. Veuillez lire attentivement les modalités énoncées dans les présentes avant d&apos;accepter le présent Contrat. Si vous n&apos;acceptez pas le présent Contrat, vous ne pouvez utiliser quelque aspect que ce soit de la Plateforme.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        La Plateforme vous est fournie en vertu du présent Contrat uniquement pour en faire un usage personnel et non commercial. La licence accordée par les présentes (voir ci-dessous) ne vous permet pas d&apos;utiliser la Plateforme sur tout Appareil (tel que défini à l&apos;article 2 ci-dessous) dont vous n&apos;êtes pas propriétaire, dont vous ne détenez pas le contrôle et que vous n&apos;avez pas le droit d&apos;utiliser, et vous ne pouvez pas distribuer ou rendre la Plateforme disponible sur un réseau où elle pourrait être utilisée par plusieurs appareils en même temps. L&apos;utilisation de la Plateforme au sein d&apos;une organisation ou l&apos;utilisation de copies multiples de la Plateforme (à l&apos;exception d&apos;une copie de sauvegarde) nécessite une licence commerciale pour la Plateforme.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Octroi de la licence&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Sous réserve de votre conformité continue au présent Contrat, Haven vous accorde par les présentes une licence limitée, non-exclusive, personnelle, révocable, sans droit de sous-licencier et non-transférable pour l&apos;utilisation de la Plateforme à des fins personnelles et ce, sur tout appareil électronique, téléphone intelligent ou tablette compatibles (« Appareils », et chacun un « Appareil »), que vous possédez ou contrôlez. Cette licence ne vous permet pas d&apos;utiliser la Plateforme sur des Appareils que vous ne possédez pas ou ne contrôlez pas. Il est de votre responsabilité de confirmer si l&apos;Appareil que vous avez choisi est compatible avec tout aspect de la Plateforme et Haven ne garantit pas que l&apos;Appareil que vous choisissez soit compatible.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Portée de la licence&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;Vous ne pourrez pas, sans le consentement de Haven:&lt;/p&gt;
      &lt;ul className="list-disc pl-6 text-muted-foreground mb-4 space-y-2"&gt;
        &lt;li&gt;copier, distribuer, partager, exécuter, transmettre, afficher, reproduire, traduire, modifier, améliorer ou créer des œuvres dérivées ou des améliorations basées sur ou à partir de la Plateforme ou fusionner, intégrer ou combiner la Plateforme avec toute autre Plateforme, sauf dans la mesure prévue dans le présent Contrat;&lt;/li&gt;
        &lt;li&gt;vendre, céder, accorder une licence, sous-licencier, divulguer, distribuer, louer, prêter ou autrement transférer ou rendre disponible la Plateforme ou toute copie de la Plateforme, peu importe sous quelle forme, à des tiers;&lt;/li&gt;
        &lt;li&gt;rétroconcevoir, désassembler, décompiler, traduire, convertir sous une forme directement lisible la Plateforme ou le code source de la Plateforme, ou autrement tenter d&apos;effectuer l&apos;une des opérations susmentionnées, sauf dans la mesure où cette interdiction n&apos;est pas autorisée par une loi applicable;&lt;/li&gt;
        &lt;li&gt;exploiter commercialement la Plateforme de quelque manière que ce soit;&lt;/li&gt;
        &lt;li&gt;supprimer, altérer, détruire ou tenter de contourner les marques de commerce, avis, codes propriétaires, notices, légendes ou marques, moyens d&apos;identification, informations relatives à la gestion des droits numériques ou contrats de licence de la Plateforme sur, dans ou en relation avec la Plateforme, ou contourner toute mesure de sécurité associée ou utiliser de toute autre manière les marques de commerce, avis, codes propriétaires, marques, légendes ou autres images contenues dans la Plateforme de quelque manière que ce soit, sauf dans la mesure permise par les présentes;&lt;/li&gt;
        &lt;li&gt;décrypter, extraire ou autrement tenter de découvrir tout code source ou secret commercial contenu dans la Plateforme ou accessible via celle-ci;&lt;/li&gt;
        &lt;li&gt;accéder à la Plateforme ou l&apos;utiliser d&apos;une manière qui n&apos;est pas autrement autorisée en vertu du présent Contrat, y compris l&apos;utilisation de la Plateforme sur un Appareil que vous ne possédez pas ou ne contrôlez pas;&lt;/li&gt;
        &lt;li&gt;accéder à la Plateforme ou l&apos;utiliser à des fins illégales ou d&apos;une manière incompatible avec toute loi ou d&apos;une manière imprudente; ou&lt;/li&gt;
        &lt;li&gt;permettre ou aider toute autre personne à utiliser la Plateforme d&apos;une manière qui constituerait une violation du présent Contrat.&lt;/li&gt;
      &lt;/ul&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous vous engagez, en outre, à ne pas utiliser la Plateforme de quelque manière à transmettre des virus, des vers ou d&apos;autres éléments malveillants ou à empiéter sur la capacité du réseau ou de quelque manière à harceler, diffamer, enfreindre ou effectuer des transmissions illégales en rapport avec l&apos;utilisation de la Plateforme ou de toute autre Plateforme de tiers.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Les modalités de ce Contrat régiront toutes les mises à jour fournies par Haven ou ses filiales qui remplacent ou complètent toute version antérieure de la Plateforme, à moins que cette mise à jour ou nouvelle version soit accompagnée d&apos;une licence séparée, auquel cas les modalités de ce contrat s&apos;appliqueront.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Titulaire de la propriété intellectuelle&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        La Plateforme est protégée par les lois canadiennes et internationales sur le droit d&apos;auteur et d&apos;autres lois sur la propriété intellectuelle, selon le cas. La Plateforme est la propriété exclusive de Haven et nonobstant toute licence contenue dans les présentes, Haven conserve tous titres, propriété, intérêt et droits dans et à la Plateforme, y compris, sans s&apos;y limiter, les brevets, les marques de commerce, les secrets commerciaux, les droits d&apos;auteur et tous les autres droits de propriété intellectuelle et industrielle, qu&apos;ils soient enregistrés ou non, dans et à la Plateforme, y compris tous les droits au code source, aux graphiques, aux images, aux marques de commerce, aux thèmes et au texte incorporé ou contenu sur la Plateforme. À l&apos;exception de la licence limitée accordée ci-dessus, rien dans le présent Contrat ne doit être interprété comme vous accordant un titre, une propriété, un intérêt ou des droits (y compris, sans s&apos;y limiter, des droits de propriété intellectuelle) dans et à la Plateforme. Tous titres, propriété, intérêt et droits qui ne sont pas expressément accordés en vertu du présent Contrat sont réservés par Haven.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Si vous faites part à Haven de vos commentaires à propos de la Plateforme (y compris toute idée ou toute suggestion d&apos;amélioration de Haven ou documentation d&apos;utilisateur connexe), Haven et ses concédants de licence, successeurs, ayants droit et titulaires de licence peuvent utiliser et/ou commercialiser ces commentaires de quelque manière et à quelque fin que ce soit, sans vous verser de compensation ou en verser une à toute autre personne.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Vie privée; consentement à la collecte et à l&apos;utilisation des données&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Haven prend votre vie privée très au sérieux. La collecte, le stockage, la divulgation et les utilisations autorisées de vos informations sont régis par la Politique de confidentialité de Haven, qui peut être consultée sur notre site. La Politique de confidentialité ainsi que ses modalités sont intégrées, par référence, au présent Contrat. En acceptant les modalités et conditions du présent Contrat, vous acceptez également les modalités de la Politique de confidentialité. Haven se réserve le droit d&apos;amender ou de modifier la Politique de confidentialité à sa seule discrétion. Vous comprenez que des tiers peuvent à tout moment collecter, stocker, divulguer ou utiliser vos informations par le biais de votre utilisation de la Plateforme et que cette collecte, ce stockage, cette divulgation ou cette utilisation par des tiers est régie par les conditions générales du tiers qui sont applicables.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Compte et identifiants&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Afin d&apos;utiliser la Plateforme, vous devez créer un compte (un « Compte ») ainsi que sélectionner et inscrire un nom d&apos;utilisateur et un mot de passe uniques (collectivement « Identifiants »). Votre Compte et vos Identifiants vous sont propres et ne peuvent être partagés avec ou transférés à toute autre personne. Vous vous assurerez que vos informations d&apos;identification demeurent sécures et confidentielles. Vous ne permettrez à aucune autre personne d&apos;utiliser votre Compte ou vos Identifiants, et vous nous informerez immédiatement si vous savez ou soupçonnez que votre Compte ou vos Identifiants ont été utilisés par une autre personne. Nous pouvons agir sur la base de toute communication donnée par le biais de votre Compte ou en utilisant vos Identifiants. Haven vérifiera l&apos;identité d&apos;un utilisateur lors de la création d&apos;un Compte. Cependant, vous acceptez que nous ne soyons pas tenus de vérifier l&apos;identité ou l&apos;autorité réelle d&apos;une personne utilisant votre Compte ou vos Identifiants après la création du Compte, mais Haven peut, à sa discrétion, exiger à tout moment la vérification de l&apos;identité d&apos;une personne cherchant à accéder à votre Compte et peut refuser l&apos;accès et l&apos;utilisation de votre Compte si nous ne sommes pas satisfaits de la vérification. Si Haven considère, à sa discrétion, que votre Compte ou vos Identifiants ne sont pas sécurisés ou qu&apos;ils ont été utilisés de manière inappropriée, nous pouvons immédiatement annuler le Compte ou les Identifiants sans vous en informer. Il peut vous être demandé de modifier vos Identifiants de temps à autre.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Services et matériel tiers&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        La Plateforme peut permettre l&apos;accès ou contenir des liens vers des services et des sites Web tiers (les « Services tiers »). Vous reconnaissez que vous avez examiné les conditions générales des Services tiers applicables lorsque ceux-ci s&apos;appliquent et que vous vous conformerez à toutes les restrictions, exigences et règles applicables qui régissent le site Web à partir duquel vous avez obtenu la Plateforme.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous acceptez qu&apos;en utilisant l&apos;un des Services tiers, vous puissiez vous heurter à du contenu qui peut être considéré comme étant offensant, indécent ou répréhensible, lequel contenu peut ou non être identifié comme comportant un langage explicite, et que les résultats de toute recherche ou saisie d&apos;un lien URL particulier peuvent automatiquement et involontairement générer des liens ou des références à du matériel répréhensible. Vous acceptez d&apos;utiliser les Services tiers à vos propres risques et vous acceptez que ni Haven ni ses filiales n&apos;auront de responsabilité envers vous pour le contenu qui peut être trouvé, via l&apos;utilisation de la Plateforme, comme étant offensant, indécent ou répréhensible.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Certains Services tiers peuvent afficher, inclure ou rendre disponible du contenu, des données, des informations, des applications, des publicités, du matériel, des sollicitations et d&apos;autres logiciels provenant de tiers, qui peuvent inclure des individus, des entreprises, des sociétés et d&apos;autres organisations (le « Matériel tiers ») ou fournir des liens vers certains sites Web tiers. En utilisant les Services tiers, vous reconnaissez et acceptez que Haven n&apos;est pas responsable de l&apos;examen, de l&apos;évaluation ou de la vérification du contenu, de l&apos;exactitude, de l&apos;exhaustivité, de l&apos;actualité, de la validité, du respect des droits d&apos;auteur, de la légalité, de la décence, de la qualité ou de tout autre aspect de ce Matériel tiers ou de ces sites Web. Les Services tiers sont mis à disposition uniquement à des fins pratiques, à des fins de divertissement et d&apos;information. Haven ne garantit pas et n&apos;endosse pas, et n&apos;assume pas et n&apos;aura pas de responsabilité envers vous ou toute autre personne pour tout Matériel tiers ou site Web tiers, ou pour tout autre matériel, produit ou service tiers. Le Matériel tiers et les liens vers d&apos;autres sites Web vous sont fournis uniquement à des fins pratiques. Les données de localisation fournies par les Services tiers sont uniquement destinées à la navigation de base et ne sont pas destinées à être utilisées dans des situations où des informations de localisation précises sont nécessaires ou lorsque des données de localisation erronées, inexactes ou incomplètes peuvent entraîner la mort, un préjudice personnel, des dommages matériels ou environnementaux. Ni Haven, ni aucun de ses fournisseurs de contenu, ne garantissent la disponibilité, l&apos;exactitude, l&apos;exhaustivité, la fiabilité ou l&apos;actualité des informations stockées ou des données de localisation affichées par les Services tiers.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous reconnaissez et acceptez que tout lien vers des Services tiers n&apos;implique en aucune façon que Haven soutienne, recommande ou approuve les Services tiers.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous reconnaissez et acceptez que les Services tiers contiennent du contenu, de l&apos;information et du matériel propriétaires qui sont détenus par des tiers et que vous êtes responsable de veiller à ce que votre utilisation des Services tiers, qu&apos;elle soit en relation avec la Plateforme ou autrement, soit conforme aux conditions d&apos;utilisation des tiers applicables et aux lois applicables.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Nulle portion des Services tiers ne peut être reproduite sous quelque forme ou par quelque moyen que ce soit. Vous acceptez de ne pas modifier, louer, prêter, vendre, distribuer ou créer des œuvres dérivées basées sur les Services tiers, de quelque manière que ce soit, et vous n&apos;exploiterez pas les Services tiers de quelque manière non autorisée quelle qu&apos;elle ce soit, y compris, mais sans s&apos;y limiter, par intrusion ou par surcharge de la capacité du réseau. Vous acceptez, en outre, de ne pas utiliser les Services tiers de quelque manière que ce soit pour harceler, abuser, traquer, menacer, diffamer ou autrement enfreindre ou violer les droits d&apos;une autre partie, et que Haven n&apos;est en aucun cas responsable d&apos;une telle utilisation par vous, ni de tout message ou toute transmission harcelant, menaçant, diffamatoire, offensant ou illégal que vous pourriez recevoir à la suite de l&apos;utilisation de l&apos;un des Services tiers.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        En outre, les Services tiers et le Matériel tiers auxquels il est possible d&apos;accéder à partir de l&apos;Appareil, ou lesquels peuvent être affichés ou liés à partir de l&apos;Appareil ne sont pas disponibles dans toutes les langues ou dans toutes les provinces ou tous les pays. Haven ne fait aucune déclaration selon laquelle ces Services tiers et Matériel tiers sont appropriés ou disponibles pour une utilisation dans un endroit particulier. Dans la mesure où vous choisissez d&apos;accéder à de tels Services tiers ou Matériel tiers, vous le faites de votre propre initiative et vous êtes responsable de la conformité à toute loi applicable, y compris, mais sans s&apos;y limiter, aux lois locales applicables. Haven et ses concédants de licence, s&apos;il y a lieu, se réservent le droit de modifier, suspendre, supprimer ou désactiver l&apos;accès à tout Service tiers à tout moment et sans préavis. En aucun cas Haven ne sera responsable de la suppression ou de la désactivation de l&apos;accès à ces Services tiers. Haven peut également imposer des limites à l&apos;utilisation ou à l&apos;accès à certains Services tiers, dans tous les cas et sans préavis ni responsabilité.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Résiliation et modification&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        La licence accordée par les présentes pour l&apos;utilisation de la Plateforme est en vigueur jusqu&apos;à sa résiliation par vous ou par Haven. Si vous ne respectez pas le présent Contrat, vos droits seront automatiquement résiliés sans préavis. Sans préjudice à ses autres droits ou recours, Haven peut résilier le présent Contrat sans motifs, à son entière discrétion, immédiatement avec ou sans préavis.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Haven peut modifier la Plateforme et le présent Contrat en vous en informant soit à votre dernière adresse électronique connue, soit en publiant un avis sur le site Web de Haven, notamment en modifiant la fonctionnalité ou l&apos;apparence de la Plateforme, ou en modifiant la portée de la licence ou d&apos;autres modalités du Contrat. Dans le cas où Haven modifie la Plateforme ou le présent Contrat, vous pouvez résilier le présent Contrat et cesser d&apos;utiliser la Plateforme.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Dans le cas où le présent Contrat est résilié conformément à l&apos;article 8, vous devez immédiatement cesser d&apos;utiliser la Plateforme et détruire toutes les copies du contenu de la Plateforme sous votre contrôle ou en votre possession. Nonobstant la résiliation du présent Contrat ou toute autre disposition contraire des présentes, les articles 4, 7, 8, 10, 11, 12, 13, 14 et 17 du présent Contrat survivront à l&apos;expiration ou à la résiliation du présent Contrat et resteront en vigueur et lieront les parties.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Mises à jour, maintenance et exigences techniques&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Haven peut, à son entière et unique discrétion, rendre disponible ou fournir des mises à jour, des mises à niveau, de la maintenance, du support en relation avec la Plateforme et/ou de nouvelles versions de la Plateforme, qui peuvent inclure des corrections de bogues, des améliorations, des nouvelles fonctionnalités, des fonctionnalités supprimées, des modifications, ou d&apos;autres améliorations (collectivement, les « Mises à jour »). Les Mises à jour peuvent entraîner la suppression de certaines caractéristiques ou fonctions. Dans la mesure où Haven publie une Mise à jour de la Plateforme, vous acceptez de cesser d&apos;utiliser la version antérieure de la Plateforme. Nonobstant ce qui précède, vous comprenez et acceptez que Haven n&apos;a aucun devoir ou aucune obligation de fournir ou de rendre disponible toute Mise à jour ou de conserver toute fonctionnalité fournie en relation avec la Plateforme ou toute Mise à jour ultérieure, et Haven ne sera en aucun cas responsable des dommages, coûts, responsabilités, frais ou dépenses que vous avez encourus découlant de ou liés à la suppression de toute fonctionnalité de la Plateforme ou de toute Mise à jour ultérieure.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous êtes seul responsable de déterminer si la Plateforme et son utilisation vous permettront d&apos;atteindre les résultats escomptés et d&apos;obtenir, de configurer et de protéger tous les équipements et services nécessaires à l&apos;installation et à l&apos;utilisation de la Plateforme et de toutes les Mises à jour, données, programmes ou Plateforme de tiers utilisés en association avec celle-ci. En aucun cas Haven ne sera responsable de ce qui précède.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Exclusion des garanties&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4 uppercase text-sm"&gt;
        VOUS RECONNAISSEZ ET ACCEPTEZ QUE VOTRE UTILISATION DE LA PLATEFORME EST À VOTRE PROPRE RISQUE. DANS TOUTE LA MESURE PERMISE PAR LA LOI APPLICABLE, LA PLATEFORME, ET TOUT LE CONTENU QUI Y FIGURE OU QUI EST DISPONIBLE OU ACCESSIBLE À PARTIR DE CELLE-CI, VOUS EST FOURNIE « TELLE QUELLE » ET AVEC TOUTES LES FAUTES ET TOUS LES DÉFAUTS, ET SANS AUCUNE DÉCLARATION ET GARANTIE, CONDITION OU GARANTIE DE QUELQUE NATURE QUE CE SOIT, QU&apos;ELLE SOIT EXPRESSE OU IMPLICITE, STATUTAIRE OU DÉCOULANT DE LA COUTUME, DU COMMERCE, DE L&apos;USAGE OU DE TOUTE PRATIQUE COMMERCIALE OU PERFORMANCE, Y COMPRIS, SANS S&apos;Y LIMITER, DES GARANTIES DE CONFORMITÉ À UN USAGE PARTICULIER, DE COMMERCIABILITÉ, DE NON-VIOLATION, DE PERFORMANCE, DE RÉSULTATS, DE COMPATIBILITÉ, DE QUALITÉ, DE RAPIDITÉ, DE TITRE, DE FABRICATION, ET SONT PAR LA PRÉSENTE EXCLUES PAR HAVEN, EN SON NOM PROPRE ET AU NOM DE SES SOCIÉTÉS AFFILIÉES, FILIALES, SUCCESSEURS ET AYANTS DROIT DANS TOUTE LA MESURE PERMISE PAR LA LOI. SANS LIMITER L&apos;ENSEMBLE DE CE QUI PRÉCÈDE, HAVEN NE FAIT AUCUNE DÉCLARATION, GARANTIE OU CONDITION SELON LAQUELLE: (I) LA PLATEFORME SERA COMPATIBLE AVEC VOS APPAREILS ET DE L&apos;ÉQUIPEMENT, DES PLATEFORMES, DES APPLICATIONS OU DES SYSTÈMES CONNEXES; (II) LA PLATEFORME SERA DISPONIBLE OU FONCTIONNERA SANS INTERRUPTION OU SERA EXEMPTE D&apos;ERREUR OU QUE TOUTE ERREUR SERA CORRIGÉE; (III) LA PLATEFORME RÉPONDRA À VOS EXIGENCES; (IV) LES DONNÉES TRAITÉES PAR LA PLATEFORME SERONT EXACTES, VALIDES, COMPLÈTES OU OPPORTUNES; (V) CERTAINS RÉSULTATS PEUVENT ÊTRE OBTENUS OU ATTEINTS PAR L&apos;UTILISATION DE LA PLATEFORME; (VI) L&apos;UTILISATION DE LA PLATEFORME SERA EXEMPTE D&apos;ERREURS, DE VIRUS OU D&apos;AUTRES ÉLÉMENTS DESTRUCTEURS OU PERTURBATEURS; OU (VII) L&apos;UTILISATION DE LA PLATEFORME NE PORTERA PAS ATTEINTE AUX DROITS (Y COMPRIS LES DROITS DE PROPRIÉTÉ INTELLECTUELLE) DE QUICONQUE. HAVEN EXCLUT TOUTE RESPONSABILITÉ À L&apos;ÉGARD DE CES ÉLÉMENTS DANS TOUTE LA MESURE PERMISE PAR LA LOI. AUCUNE INFORMATION OU CONSEIL ORAL OU ÉCRIT DONNÉ PAR LE CONCÉDANT OU SES REPRÉSENTANTS AUTORISÉS NE CRÉERA DE GARANTIE.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4 uppercase text-sm"&gt;
        CERTAINES JURIDICTIONS N&apos;AUTORISENT PAS L&apos;EXCLUSION OU LA LIMITATION DES GARANTIES IMPLICITES OU LA LIMITATION DES DROITS STATUTAIRES D&apos;UN CONSOMMATEUR QUI SONT APPLICABLES, DE SORTE QUE TOUT OU PARTIE DES EXCLUSIONS ET DES LIMITATIONS CI-DESSUS PEUVENT NE PAS S&apos;APPLIQUER À VOUS.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Limitation de responsabilité&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4 uppercase text-sm"&gt;
        DANS TOUTE LA MESURE PERMISE PAR LA LOI APPLICABLE ET NONOBSTANT TOUTE AUTRE DISPOSITION DU PRÉSENT CONTRAT, EN AUCUN CAS HAVEN, SES SOCIÉTÉS AFFILIÉES, SUCCESSEURS OU AYANTS DROIT, OU L&apos;UN DE SES OU DE LEURS CONCÉDANTS, PRESTATAIRES DE SERVICES, EMPLOYÉS, AGENTS, REPRÉSENTANTS, COMMANDITAIRES, PARTENAIRES, DIRIGEANTS, ADMINISTRATEURS, CADRES ET/OU MEMBRES RESPECTIFS NE POURRONT ÊTRE TENUS RESPONSABLES ENVERS VOUS DE TOUT PRÉJUDICE, PERSONNEL OU AUTRE, ET DE TOUT MONTANT, OU DE TOUTE PERTE, RÉCLAMATION, RÉCLAMATIONS DE TIERS SELON LESQUELLES LA PLATEFORME ENFREINT LES DROITS DE PROPRIÉTÉ INTELLECTUELLE D&apos;UN TIERS, LES PRÉJUDICES OU LES DOMMAGES ACCESSOIRES, SPÉCIAUX, PUNITIFS, EXEMPLAIRES, INDIRECTS OU CONSÉCUTIFS QUELS QU&apos;ILS SOIENT, Y COMPRIS LES DOMMAGES POUR PERTE DE REVENUS, PERTE COMMERCIALE, PERTE DE DONNÉES, PERTE DE FONDS DE COMMERCE, D&apos;ÉCONOMIES, DE REVENUS, DE BÉNÉFICES, D&apos;UTILISATION, DE PRODUCTION ANTICIPÉE, D&apos;INTERRUPTION COMMERCIALE, DE DÉFÉCTUOSITÉ OU AUTRE, L&apos;INCAPACITÉ À FOURNIR UN SUPPORT, DES MISES À JOUR, UNE MAINTENANCE OU TOUT AUTRE DOMMAGE OU PERTE COMMERCIALES DÉCOULANT DE OU LIÉ À VOTRE UTILISATION DE LA PLATEFORME, QUELLE QU&apos;EN SOIT LA CAUSE.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4 uppercase text-sm"&gt;
        CE QUI PRÉCÈDE N&apos;AFFECTE PAS LA RESPONSABILITÉ QUI NE PEUT PAS ÊTRE EXCLUE OU LIMITÉE EN VERTU DE LA LOI APPLICABLE. CEPENDANT, DANS TOUTE LA MESURE PERMISE PAR LA LOI APPLICABLE, LES LIMITATIONS PRÉCÉDENTES S&apos;APPLIQUERONT, QUE CES DOMMAGES RÉSULTENT D&apos;UNE VIOLATION DE CONTRAT, D&apos;UN DÉLIT CIVIL (Y COMPRIS LA NÉGLIGENCE) OU AUTRE, ET QUE CES DOMMAGES AIENT ÉTÉ PRÉVISIBLES OU QUE HAVEN AIT ÉTÉ INFORMÉE DE LA POSSIBILITÉ DE TELS DOMMAGES.
      &lt;/p&gt;
      &lt;p className="text-muted-foreground mb-4 uppercase text-sm"&gt;
        CERTAINES JURIDICTIONS N&apos;AUTORISENT PAS CERTAINES LIMITATIONS DE RESPONSABILITÉ, DE SORTE QUE TOUT OU UNE PARTIE DES LIMITATIONS DE RESPONSABILITÉ CI-DESSUS PEUVENT NE PAS S&apos;APPLIQUER À VOUS.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Recours exclusif&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Dans toute la mesure permise par la loi applicable, votre seul recours en ce qui concerne l&apos;utilisation de la Plateforme sera de résilier le présent Contrat et la licence accordée en vertu des présentes et de cesser d&apos;utiliser la Plateforme.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Libération et quittance&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous êtes seul responsable de l&apos;utilisation de la Plateforme et de vos interactions avec les commerçants et les autres sites. Dans la mesure où la loi applicable le permet, vous libérez Haven de toute réclamation, demande, procédure ou responsabilité liée aux Services tiers ou au Matériel tiers, y compris en ce qui concerne toutes offres, produits ou services.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Indemnisation&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous et toute personne que vous représentez et qui utilise la Plateforme, indemniserez, défendrez et tiendrez à couvert Haven et ses dirigeants, employeurs, employés, entrepreneurs, personnel, commanditaires, gestionnaires, agents, sociétés mères, filiales, représentants affiliés et autres partenaires de tout dommage direct, indirect, accessoire, spécial, ou exemplaire contre toute réclamation, demande, poursuite, procédure, quelle qu&apos;elle soit, menacée ou en cours, directement ou indirectement, découlant de, liée à ou relative à, votre utilisation de la Plateforme, toute autre question relative à la Plateforme et/ou toute négligence, mauvaise conduite, ou la violation du présent Contrat par vous.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Respect des lois applicables&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Vous acceptez d&apos;utiliser la Plateforme en conformité avec toutes les lois et réglementations locales, étatiques, provinciales, nationales et étrangères applicables, y compris toutes les lois d&apos;exportation applicables. Vous déclarez et garantissez à Haven que vous n&apos;êtes pas situé dans un pays où votre utilisation de la Plateforme violerait les lois locales ou étrangères. Haven se réserve le droit de modifier, suspendre, supprimer ou désactiver l&apos;accès à la Plateforme à tout moment et sans préavis. En aucun cas, Haven ne sera responsable de la suppression ou de la désactivation de l&apos;accès à une telle Plateforme.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Lois applicables&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Le présent Contrat, la Plateforme et son utilisation sont régis par les lois de la province de l&apos;Ontario et les lois fédérales du Canada qui y sont applicables. Chacune des parties aux présentes reconnaît et se soumet irrévocablement à la juridiction exclusive des tribunaux de la province de l&apos;Ontario et accepte en outre de soumettre tout litige qui pourrait survenir en vertu des présentes aux tribunaux situés dans le district judiciaire de Toronto, province de l&apos;Ontario.
      &lt;/p&gt;

      &lt;h2 className="text-2xl font-heading font-semibold mt-8 mb-4"&gt;Général&lt;/h2&gt;
      &lt;p className="text-muted-foreground mb-4"&gt;
        Le présent Contrat constitue l&apos;intégralité du Contrat entre vous et Haven et remplace toute autre communication ou publicité relative à la Plateforme. Haven peut modifier ou changer les modalités de ce Contrat de temps à autre à sa seule discrétion. Vous ne pouvez pas céder ce Contrat sans le consentement de Haven, lequel consentement peut être refusé à la seule discrétion de Haven. Haven peut céder ce contrat à sa seule discrétion sans avoir besoin d&apos;obtenir votre consentement. Aucun consentement ou renonciation à l&apos;égard de vos obligations en vertu des présentes ne sera effectif à moins d&apos;être par écrit et signé par Haven. Si l&apos;une des dispositions du présent Contrat est jugée invalide ou inapplicable, les autres dispositions du présent Contrat continueront à produire tous leurs effets sans être altérées ou invalidées de quelque manière que ce soit. Dans le présent Contrat: (a) les titres ne sont donnés qu&apos;à titre indicatif; (b) le terme « personne » inclut une entité juridique; (c) les mots au singulier incluent le pluriel, et vice versa; (d) les mots au masculin incluent les deux genres; et (e) « incluant » ou « inclut » signifie incluant ou inclut (selon le cas) sans limitation ou restriction.
      &lt;/p&gt;
    &lt;/div&gt;
  )
}
